language: node_js
node_js:
  - 14
sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t minotep/docker-react .
script:
  - docker run -e CI=true minotep/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-034093998447"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
