language: node_js
node_js:
  - 14
sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t minotep/docker-react .
script:
  - docker run -e CI=true minotep/docker-react npm run test -- --coverage
